package com.docspot.enums;

public enum Speciality {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC,
    PEDIATRICIAN,
    PSYCHIATRIST,
    GYNECOLOGIST,
    OPHTHALMOLOGIST,
    ENT_SPECIALIST,
    DENTIST,
    RADIOLOGIST,
    UROLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    PULMONOLOGIST,
    ONCOLOGIST,
    NEPHROLOGIST,
    RHEUMATOLOGIST,
    OTHER
}